baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Eco-pallets'
defaultContentLanguage = 'en'
[languages]
  [languages.uk]
    contentDir = 'content/uk'
    languageCode = 'uk-UA'
    languageName = 'Ukrainian'
    title = ''
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en-US'
    languageName = 'English'
    title = ''
  [languages.fr]
    contentDir = 'content/fr'
    languageCode = 'fr-FR'
    languageName = 'French'
    title = ''
  [languages.de]
    contentDir = 'content/de'
    languageCode = 'de-DE'
    languageName = 'German'
    title = ''
  [languages.it]
    contentDir = 'content/it'
    languageCode = 'it-IT'
    languageName = 'Italian'
    title = ''
  [languages.pl]
    contentDir = 'content/pl'
    languageCode = 'pl-PL'
    languageName = 'Polish'
    title = ''
  