backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/_index.md'
        label: 'Main Page'
        name: 'main'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - {
            label: 'Hero',
            name: 'hero',
            widget: 'object',
            fields:
              [
                { label: 'Heading', name: 'heading', widget: 'string' },
                { label: 'Subheading', name: 'subheading', widget: 'string' },
                { label: 'Background Image', name: 'background', widget: 'image' },
              ]
            }