backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
locale: 'uk'
i18n:
  structure: multiple_folders
  locales: [uk, en, fr, de, it, pl]
  default_locale: uk
collections:
  - label: 'Головна сторінка'
    name: 'main-page'
    folder: 'content'
    i18n: true
    fields:
      - label: 'Головна секція'
        name: 'hero'
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'markdown', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Текст', name: 'text', widget: 'string', i18n: true }
          - { label: 'Зображення', name: 'image', widget: 'image', i18n: true }
      - label: 'Про нас'
        name: 'about'
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'string', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Текст', name: 'text', widget: 'object', i18n: true, 
              fields: [
                { label: 'Видимий текст', name: 'visible', widget: 'text', i18n: true },
                { label: 'Схований текст', name: 'hidden', widget: 'text', i18n: true },
              ]
            }
          - { label: 'Зображення', name: 'image', widget: 'image', i18n: true }
      - label: 'Продукція'
        name: 'products'
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'string', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Підзаголовок', name: 'subtitle', widget: 'string', i18n: true }
          - { label: 'Список продуктів', name: 'list', widget: 'list', i18n: true,
              fields: [
                { label: 'Назва продукту', name: 'name', widget: 'string', i18n: true },
                { label: 'Зображення', name: 'image', widget: 'image', i18n: true },
                { lable: 'Повна інформація', name: 'modal', widget: 'object', i18n: true,
                  fields: [
                    { label: 'Заголовок', name: 'title', widget: 'string', i18n: true },
                    { label: 'Текст', name: 'text', widget: 'markdown', i18n: true },
                    { label: 'Зображення', name: 'image', widget: 'image', i18n: true },
                  ]
                }
              ]
            }
          - { label: 'Спецзамовлення', name: 'special', widget: 'object', i18n: true,
              fields: [
                { label: 'Заголовок', name: 'title', widget: 'string', i18n: true },
                { label: 'Текст', name: 'text', widget: 'text', i18n: true },
              ]
            }
      - label: 'Послуги'
        name: 'services'
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'string', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Список послуг', name: 'services', widget: 'list', i18n: true, field: { label: 'Назва послуги', name: 'name', widget: 'string', i18n: true } }
      - label: 'Переваги'
        name: 'pros'
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'string', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Список переваг', name: 'pros', widget: 'list', min: 5, max: 5, i18n: true,
              fields: [
                { label: 'Назва переваги', name: 'name', widget: 'string', i18n: true },
                { label: 'Текст', name: 'text', widget: 'text', i18n: true },
                { label: 'Зображення', name: 'image', widget: 'image', i18n: true },
              ]
            }
          - { label: 'CTA', name: 'cta', widget: 'string', i18n: true }
      - label: 'Сертифікати'
        name: 'cert'
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'string', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
      - name: 'form'
        label: "Форма зворотнього зв'язку"
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'string', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Типи товарів', name: 'types', widget: 'list', i18n: true,
              field: { label: 'Назва типу', name: 'name', widget: 'string', i18n: true }
            }
      - name: 'contacts'
        label: 'Контакти'
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'string', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Виробництво', name: 'assembly', widget: 'object', i18n: true,
              fields: [
                { label: 'Локація', name: 'location', widget: 'string', i18n: true },
                { label: 'Посилання на локацію', name: 'locationLink', widget: 'string', i18n: true },
                { label: 'Телефон', name: 'phone', widget: 'string', i18n: true },
                { label: 'Email', name: 'email', widget: 'string', i18n: true },
              ]
            }
          - { label: 'Склад в Європі', name: 'euStorage', widget: 'object', i18n: true,
              fields: [
                { label: 'Локація', name: 'location', widget: 'string', i18n: true },
                { label: 'Посилання на локацію', name: 'locationLink', widget: 'string', i18n: true },
              ]
            }
      - label: 'Утиліти'
        name: 'utils'
        widget: 'object'
        i18n: true
        fields:
          - { label: 'Посилання LinkedIn', name: 'linkedIn', widget: 'string', i18n: true }
          - { label: 'Навігація', name: 'nav', widget: 'object', i18n: true,
              fields: [
                { label: 'Про нас', name: 'about', widget: 'string', i18n: true },
                { label: 'Продукти', name: 'products', widget: 'string', i18n: true },
                { label: 'Послуги', name: 'services', widget: 'string', i18n: true },
                { label: 'Чому ми?', name: 'pros', widget: 'string', i18n: true },
                { label: 'Сертифікати', name: 'cert', widget: 'string', i18n: true },
                { label: 'Контакти', name: 'contacts', widget: 'string', i18n: true },
              ]
            }
          - { label: 'Кнопки', name: 'btns', widget: 'object', i18n: true,
              fields: [
                { label: "Зв'язок з нами", name: 'call', widget: 'string', i18n: true },
                { label: 'Наші продукти', name: 'products', widget: 'string', i18n: true },
                { label: 'Детальніше', name: 'more', widget: 'string', i18n: true },
                { label: 'Зробити замовлення', name: 'order', widget: 'string', i18n: true },
                { labels: 'Показати на мапі', name: 'showOnMap', widget: 'string', i18n: true}
              ]
            }
          - { label: 'Шаблони для полів', name: 'placeholders', widget: 'object', i18n: true,
              fields: [
                { label: "Ім'я", name: 'name', widget: 'string', i18n: true },
                { label: 'Email', name: 'email', widget: 'string', i18n: true },
                { label: 'Повідомлення', name: 'message', widget: 'string', i18n: true },
              ]
            }
