backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'main-page'
    label: 'Main Page'
    files:
      - file: 'content/hero.md'
        label: 'Головна секція'
        name: 'main-section'
        fields:
          - { label: 'Головна секція', name: 'content', widget: 'object',
              fields: [
                { label: 'Заголовок', name: 'title', widget: 'string' },
                { label: 'Текст', name: 'text', widget: 'string' },
                { label: 'Зображення', name: 'image', widget: 'image' },
              ]
            }
      - file: 'content/about.md'
        label: 'Про нас'
        name: 'about'
        fields:
          - { label: 'Про нас', name: 'content', widget: 'object',
              fields: [
                { label: 'Заголовок', name: 'title', widget: 'string' },
                { label: 'Текст', name: 'text', widget: 'object',
                  fields: [
                    { label: 'Видимий текст', name: 'visible', widget: 'text' },
                    { label: 'Схований текст', name: 'hidden', widget: 'text' },
                  ]
                },
                { label: 'Зображення', name: 'image', widget: 'image' },
              ]
            }
      - file: 'content/products.md'
        label: 'Продукція'
        name: 'products'
        fields:
          - { label: 'Продукція', name: 'content', widget: 'object',
              fields: [
                { label: 'Заголовок', name: 'title', widget: 'string' },
                { label: 'Підзаголовок', name: 'subtitle', widget: 'string' },
                { label: 'Список продуктів', name: 'list', widget: 'list',
                  fields: [
                    { label: 'Назва продукту', name: 'name', widget: 'string' },
                    { label: 'Зображення', name: 'image', widget: 'image' },
                  ]
                },
                { label: 'Спецзамовлення', name: 'special', widget: 'object',
                  fields: [
                    { label: 'Заголовок', name: 'title', widget: 'string' },
                    { label: 'Текст', name: 'text', widget: 'text' },
                  ]
                }
              ]
            }
      - file: 'content/services.md'
        label: 'Послуги'
        name: 'services'
        fields:
          - { label: 'Послуги', name: 'content', widget: 'object',
              fields: [
                { label: 'Заголовок', name: 'title', widget: 'string' },
                { label: 'Список послуг', name: 'services', widget: 'list',
                  field: { label: 'Назва послуги', name: 'name', widget: 'string' } 
                },
              ]
            }
      - file: 'content/pros.md'
        label: 'Переваги'
        name: 'pros'
        fields:
          - { label: 'Переваги', name: 'content', widget: 'object',
              fields: [
                { label: 'Заголовок', name: 'title', widget: 'string' },
                { label: 'Список переваг', name: 'pros', widget: 'list', allow_add: false,
                  fields: [
                    { label: 'Назва переваги', name: 'name', widget: 'string' },
                    { label: 'Текст', name: 'text', widget: 'text' },
                    { label: 'Зображення', name: 'image', widget: 'image' },
                  ],
                  default: [
                    { name: 'Матеріали найвищої якості', text: 'Використовуємо якісні екологічні матеріали, завдяки чому наша продукція довго залишатиметься практичною, міцною, зручною та безпечною.', image: '/img/leafs-icon.svg' },
                    { name: 'Відповідність технічному завданню', text: 'Маємо автоматичні лінії для збивання піддонів, коління дров, пилорами та багато інших устаткувань, що забезпечує високу точність виробництва у суворій відповідності до технічного завдання.', image: '/img/mechanism-icon.svg'},
                    { name: 'Широкий ассортимент', text: 'Виготовляємо понад 50 видів товарів, а також можемо реалізувати індивідуальне замовлення. Можемо постачати малі та великі обсяги в короткі терміни. Необхідна кількість піддонів завжди в наявності на складах, завдяки чому ви отримаєте своє замовлення якомога швидше.', image: '/img/layers-icon.svg'},
                    { name: 'Нові та вживані товари', text: 'Пропонуємо як нові, так й вживані товари, тому кожен клієнт може підібрати продукцію, яка влаштує його за якістю та ціною.', image: '/img/shapes-icon.svg'},
                    { name: 'Європейська сертифікація EPAL', text: 'Реалізуємо кращі палети, стандартизовані під європейську сертифікацію: маємо всі потрібні сертифікати якості та виробляємо продукцію згідно з прийнятими в Європі нормами.', image: '/img/cert-icon.svg'},
                  ]
                },
                { label: 'CTA', name: 'cta', widget: 'string' }
              ]
            }
      - file: 'content/cert.md'
        label: 'Сертифікати'
        name: 'cert'
        fields:
          - { label: 'Сертифікати', name: 'content', widget: 'object',
              fields: [
                { label: 'Заголовок', name: 'title', widget: 'string' },
              ]
            }
      # - name: 'form'
      #   file: 'content/form.md'
      #   label: 'Форма зворотнього зв\'язку'
      #   fields:
      #     - { label: 'Форма зворотнього зв\'язку', name: 'content', widget: 'object',
      #         fields: [
      #           { label: 'Заголовок', name: 'title', widget: 'string' },
      #           { label: 'Типи товарів', name: 'types', widget: 'list', 
      #             field: { label: 'Назва типу', name: 'name', widget: 'string' },
      #           },
      #         ]
      #       }