backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'main-page'
    label: 'Main Page'
    files:
      - file: 'content/hero.md'
        label: 'Головна секція'
        name: 'main-section'
        fields:
          - { label: 'Головна секція', name: 'content', widget: 'object',
              fields: [
                { label: 'Лейбл', name: 'label', widget: 'object',
                  fields: [
                    { label: 'Число', name: 'number', widget: 'string', required: false },
                    { label: 'Текст', name: 'text', widget: 'string' },
                  ] 
                },
                { label: 'Заголовок', name: 'title', widget: 'string' },
                { label: 'Текст', name: 'text', widget: 'string' },
                { label: 'Зображення', name: 'image', widget: 'image' },
              ]
            }
      - file: 'content/about.md'
        label: 'Про нас'
        name: 'about'
        fields:
          - { label: 'Про нас', name: 'content', widget: 'object',
              fields: [
                { label: 'Лейбл', name: 'label', widget: 'string' },
                { label: 'Заголовок', name: 'title', widget: 'string' },
                { label: 'Текст', name: 'text', widget: 'object',
                  fields: [
                    { label: 'Видимий текст', name: 'visible', widget: 'string' },
                    { label: 'Схований текст', name: 'hidden', widget: 'string' },
                  ]
                },
                { label: 'Зображення', name: 'image', widget: 'image' },
              ]
            }