backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: assets/images
public_folder: /images
locale: 'uk'
i18n:
  structure: multiple_folders
  locales: [ua, pl, en, fr, de, it]
  default_locale: ua
collections:
  - label: 'Головна сторінка'
    name: 'main-page'
    folder: 'content'
    i18n: true
    fields:
      - {label: "title", name: "title", widget: "string", default: 'Вміст', required: false}
      - label: 'Головна секція'
        name: 'hero'
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Текст', name: 'text', widget: 'string', i18n: true }
          - { label: 'Зображення', name: 'image', widget: 'image', i18n: true }
      - label: 'Про нас'
        name: 'about'
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'string', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Текст', name: 'text', widget: 'object', i18n: true, 
              fields: [
                { label: 'Видимий текст', name: 'visible', widget: 'markdown', i18n: true, buttons: [], editor_components: [] },
                { label: 'Схований текст', name: 'hidden', widget: 'markdown', i18n: true, buttons: [], editor_components: [] },
              ]
            }
          - { label: 'Статистики', name: 'stats', widget: 'object', i18n: true, 
              fields: [
                { label: 'Заголовок про піддони', name: 'palletsTitle', widget: 'string', i18n: true },
                { label: 'Текст про піддони', name: 'palletsText', widget: 'string', i18n: true },
                { label: 'Заголовок про працівників', name: 'employeesTitle', widget: 'string', i18n: true },
                { label: 'Текст про працівників', name: 'employeesText', widget: 'string', i18n: true },
              ]
            }
          - { label: 'Відео', name: 'video', widget: 'file', i18n: true }
      - label: 'Продукція'
        name: 'products'
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'string', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Підзаголовок', name: 'subtitle', widget: 'string', i18n: true }
          - { label: 'Список продуктів', name: 'list', widget: 'list', i18n: true,
              fields: [
                { label: 'Назва продукту', name: 'name', widget: 'string', i18n: true },
                { label: 'Зображення', name: 'image', widget: 'image', i18n: true },
                { lable: 'Повна інформація', name: 'modal', widget: 'object', i18n: true,
                  fields: [
                    { label: 'Заголовок', name: 'title', widget: 'string', i18n: true },
                    { label: 'Текст', name: 'text', widget: 'markdown', i18n: true, buttons: ['italic', 'bold', 'bulleted-list', 'heading-three'], editor_components: [] },
                    { label: 'Зображення', name: 'image', widget: 'image', i18n: true },
                  ]
                }
              ]
            }
          - { label: 'Спецзамовлення', name: 'special', widget: 'object', i18n: true,
              fields: [
                { label: 'Заголовок', name: 'title', widget: 'string', i18n: true },
                { label: 'Текст', name: 'text', widget: 'text', i18n: true },
              ]
            }
      - label: 'Послуги'
        name: 'services'
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'string', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Список послуг', name: 'services', widget: 'list', i18n: true, field: { label: 'Назва послуги', name: 'name', widget: 'string', i18n: true } }
      - label: 'Переваги'
        name: 'pros'
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'string', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Список переваг', name: 'pros', widget: 'list', min: 5, max: 5, i18n: true,
              fields: [
                { label: 'Назва переваги', name: 'name', widget: 'string', i18n: true },
                { label: 'Текст', name: 'text', widget: 'text', i18n: true },
                { label: 'Зображення', name: 'image', widget: 'image', i18n: true },
              ]
            }
          - { label: 'CTA', name: 'cta', widget: 'string', i18n: true }
      - label: 'Сертифікати'
        name: 'cert'
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'string', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Сертифікати', name: 'list', widget: 'object', i18n: true,
              fields: [
                { label: 'EPAL', name: 'cert1', widget: 'string', i18n: true },
                { label: 'Фітосанітарний сертифікат', name: 'cert2', widget: 'string', i18n: true },
                { label: 'Санітарно-епідеміологічна експертиза', name: 'cert3', widget: 'string', i18n: true },
              ]
            }
      - name: 'form'
        label: "Форма зворотнього зв'язку"
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'string', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Заголовок типу товарів', name: 'typesTitle', widget: 'string', i18n: true }
          - { label: 'Типи товарів', name: 'types', widget: 'list', i18n: true,
              field: { label: 'Назва типу', name: 'name', widget: 'string', i18n: true }
            }
      - name: 'contacts'
        label: 'Контакти'
        i18n: true
        widget: 'object'
        required: false
        fields:
          - { label: 'Лейбл', name: 'label', widget: 'string', i18n: true }
          - { label: 'Заголовок', name: 'title', widget: 'string', i18n: true }
          - { label: 'Виробництво', name: 'assembly', widget: 'object', i18n: true,
              fields: [
                { label: 'Лейбл', name: 'label', widget: 'string', i18n: true },
                { label: 'Локація', name: 'location', widget: 'string', i18n: true },
                { label: 'Посилання на локацію', name: 'locationLink', widget: 'string', i18n: true },
                { label: 'Телефон', name: 'phone', widget: 'string', i18n: true },
                { label: 'Email', name: 'email', widget: 'string', i18n: true },
              ]
            }
          - { label: 'Склад в Європі', name: 'euStorage', widget: 'object', i18n: true,
              fields: [
                { label: 'Лейбл', name: 'label', widget: 'string', i18n: true },
                { label: 'Локація', name: 'location', widget: 'string', i18n: true },
                { label: 'Посилання на локацію', name: 'locationLink', widget: 'string', i18n: true },
              ]
            }
      - label: 'Утиліти'
        name: 'utils'
        widget: 'object'
        i18n: true
        fields:
          - { label: 'Посилання LinkedIn', name: 'linkedIn', widget: 'string', i18n: true }
          - { label: 'Навігація', name: 'nav', widget: 'object', i18n: true,
              fields: [
                { label: 'Про нас', name: 'about', widget: 'string', i18n: true },
                { label: 'Продукти', name: 'products', widget: 'string', i18n: true },
                { label: 'Послуги', name: 'services', widget: 'string', i18n: true },
                { label: 'Чому ми?', name: 'pros', widget: 'string', i18n: true },
                { label: 'Сертифікати', name: 'cert', widget: 'string', i18n: true },
                { label: 'Контакти', name: 'contacts', widget: 'string', i18n: true },
              ]
            }
          - { label: 'Кнопки', name: 'btns', widget: 'object', i18n: true,
              fields: [
                { label: "Зв'язок з нами", name: 'call', widget: 'string', i18n: true },
                { label: 'Наші продукти', name: 'products', widget: 'string', i18n: true },
                { label: 'Детальніше', name: 'more', widget: 'string', i18n: true },
                { label: 'Зробити замовлення', name: 'order', widget: 'string', i18n: true },
                { labels: 'Показати на мапі', name: 'showOnMap', widget: 'string', i18n: true}
              ]
            }
          - { label: 'Шаблони для полів', name: 'placeholders', widget: 'object', i18n: true,
              fields: [
                { label: "Ім'я", name: 'name', widget: 'string', i18n: true },
                { label: 'Email', name: 'email', widget: 'string', i18n: true },
                { label: 'Повідомлення', name: 'message', widget: 'string', i18n: true },
              ]
            }
          - { label: 'Повідомлення валідації', name: 'validation', widget: 'object', i18n: true,
              fields: [
                { label: 'Неправильний формат пошти', name: 'invalidEmail', widget: 'string', i18n: true },
                { label: 'Телефон обов`язковий', name: 'requiredPhone', widget: 'string', i18n: true },
                { label: 'Направильний формат номеру', name: 'invalidPhone', widget: 'string', i18n: true },
                { label: "Тип продукту обо'язковий", name: 'requiredProductType', widget: 'string', i18n: true },
                { label: "Капчя обо'язкова", name: 'captchaRequired', widget: 'string', i18n: true }
              ]
            }
          - { label: 'Повідомлення про відправку', name: 'success', widget: 'markdown', i18n: true, minimal: true, buttons: [] }
